"""empty message

Revision ID: 0d688175182d
Revises: 3b5e62c7c4e1
Create Date: 2016-08-01 09:39:34.864433

"""

# revision identifiers, used by Alembic.
revision = '0d688175182d'
down_revision = '3b5e62c7c4e1'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vul_reports', sa.Column('done_solution', sa.Text(), nullable=True))
    op.add_column('vul_reports', sa.Column('end_date', sa.Date(), nullable=True))
    op.add_column('vul_reports', sa.Column('fix_date', sa.Date(), nullable=True))
    op.add_column('vul_reports', sa.Column('grant_rank', sa.Integer(), nullable=True))
    op.add_column('vul_reports', sa.Column('person_score', sa.Integer(), nullable=True))
    op.add_column('vul_reports', sa.Column('residual_risk_score', sa.String(length=64), nullable=True))
    op.add_column('vul_reports', sa.Column('risk_score', sa.String(length=64), nullable=True))
    op.add_column('vul_reports', sa.Column('start_date', sa.Date(), nullable=True))
    op.add_column('vul_reports', sa.Column('vul_status', sa.String(length=64), nullable=True))
    op.add_column('vul_reports', sa.Column('vul_type_level', sa.String(length=64), nullable=True))
    op.drop_column('vul_reports', 'vul_self_level')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vul_reports', sa.Column('vul_self_level', mysql.VARCHAR(length=64), nullable=True))
    op.drop_column('vul_reports', 'vul_type_level')
    op.drop_column('vul_reports', 'vul_status')
    op.drop_column('vul_reports', 'start_date')
    op.drop_column('vul_reports', 'risk_score')
    op.drop_column('vul_reports', 'residual_risk_score')
    op.drop_column('vul_reports', 'person_score')
    op.drop_column('vul_reports', 'grant_rank')
    op.drop_column('vul_reports', 'fix_date')
    op.drop_column('vul_reports', 'end_date')
    op.drop_column('vul_reports', 'done_solution')
    ### end Alembic commands ###
