"""empty message

Revision ID: 1f593ad2c634
Revises: 206f0f4f24a8
Create Date: 2016-07-28 23:28:48.193428

"""

# revision identifiers, used by Alembic.
revision = '1f593ad2c634'
down_revision = '206f0f4f24a8'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vul_reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('author', sa.String(length=64), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('title', sa.String(length=128), nullable=True),
    sa.Column('related_asset', sa.String(length=64), nullable=True),
    sa.Column('related_vul_type', sa.String(length=64), nullable=True),
    sa.Column('vul_self_rank', sa.Integer(), nullable=True),
    sa.Column('vul_self_level', sa.String(length=64), nullable=True),
    sa.Column('vul_source', sa.String(length=64), nullable=True),
    sa.Column('vul_poc', sa.Text(), nullable=True),
    sa.Column('vul_poc_html', sa.Text(), nullable=True),
    sa.Column('vul_solution', sa.Text(), nullable=True),
    sa.Column('vul_solution_html', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vul_reports_author'), 'vul_reports', ['author'], unique=False)
    op.create_index(op.f('ix_vul_reports_timestamp'), 'vul_reports', ['timestamp'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_vul_reports_timestamp'), table_name='vul_reports')
    op.drop_index(op.f('ix_vul_reports_author'), table_name='vul_reports')
    op.drop_table('vul_reports')
    ### end Alembic commands ###
