"""empty message

Revision ID: 206f0f4f24a8
Revises: 744baa3a5718
Create Date: 2016-07-25 10:16:08.873567

"""

# revision identifiers, used by Alembic.
revision = '206f0f4f24a8'
down_revision = '744baa3a5718'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('login_users', sa.Column('related_name', sa.String(length=64), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('login_users', 'related_name')
    ### end Alembic commands ###
