"""empty message

Revision ID: 29caab165b4d
Revises: 5d97b1d70bfe
Create Date: 2016-07-04 14:24:46.564902

"""

# revision identifiers, used by Alembic.
revision = '29caab165b4d'
down_revision = '5d97b1d70bfe'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_departs_email', table_name='departs')
    op.create_index(op.f('ix_departs_email'), 'departs', ['email'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_departs_email'), table_name='departs')
    op.create_index('ix_departs_email', 'departs', ['email'], unique=1)
    ### end Alembic commands ###
