"""empty message

Revision ID: 2a6d3c1ab567
Revises: None
Create Date: 2016-06-29 17:36:53.071382

"""

# revision identifiers, used by Alembic.
revision = '2a6d3c1ab567'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sysname', sa.String(length=64), nullable=True),
    sa.Column('domain', sa.String(length=64), nullable=True),
    sa.Column('root_dir', sa.String(length=64), nullable=True),
    sa.Column('back_domain', sa.String(length=100), nullable=True),
    sa.Column('web_or_int', sa.String(length=64), nullable=True),
    sa.Column('is_http', sa.Boolean(), nullable=True),
    sa.Column('is_https', sa.Boolean(), nullable=True),
    sa.Column('in_or_out', sa.String(length=64), nullable=True),
    sa.Column('level', sa.String(length=64), nullable=True),
    sa.Column('department', sa.String(length=64), nullable=True),
    sa.Column('owner', sa.String(length=64), nullable=True),
    sa.Column('status', sa.String(length=64), nullable=True),
    sa.Column('ps', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_assets_domain'), 'assets', ['domain'], unique=True)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_assets_domain'), table_name='assets')
    op.drop_table('assets')
    ### end Alembic commands ###
