"""empty message

Revision ID: 3b5e62c7c4e1
Revises: 0a7d298bcc36
Create Date: 2016-08-01 03:27:00.015971

"""

# revision identifiers, used by Alembic.
revision = '3b5e62c7c4e1'
down_revision = '0a7d298bcc36'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vul_reports', sa.Column('related_asset_inout', sa.String(length=64), nullable=True))
    op.add_column('vul_reports', sa.Column('related_asset_status', sa.String(length=64), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vul_reports', 'related_asset_status')
    op.drop_column('vul_reports', 'related_asset_inout')
    ### end Alembic commands ###
