"""empty message

Revision ID: 5d97b1d70bfe
Revises: bc8a1a1a19bf
Create Date: 2016-07-04 14:03:52.148852

"""

# revision identifiers, used by Alembic.
revision = '5d97b1d70bfe'
down_revision = 'bc8a1a1a19bf'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('departs', sa.Column('email', sa.String(length=64), nullable=True))
    op.create_index(op.f('ix_departs_email'), 'departs', ['email'], unique=True)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_departs_email'), table_name='departs')
    op.drop_column('departs', 'email')
    ### end Alembic commands ###
