"""empty message

Revision ID: 6e6dcb77d916
Revises: c850f23efd3c
Create Date: 2016-07-04 11:07:26.055772

"""

# revision identifiers, used by Alembic.
revision = '6e6dcb77d916'
down_revision = 'c850f23efd3c'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vul_ranks', sa.Column('vul_id', sa.String(length=64), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vul_ranks', 'vul_id')
    ### end Alembic commands ###
