"""empty message

Revision ID: 744baa3a5718
Revises: 702899568dee
Create Date: 2016-07-23 02:44:00.433495

"""

# revision identifiers, used by Alembic.
revision = '744baa3a5718'
down_revision = '702899568dee'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('login_users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=64), nullable=True),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('role_name', sa.String(length=64), nullable=True),
    sa.Column('confirmed', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_login_users_email'), 'login_users', ['email'], unique=True)
    op.create_index(op.f('ix_login_users_username'), 'login_users', ['username'], unique=True)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_login_users_username'), table_name='login_users')
    op.drop_index(op.f('ix_login_users_email'), table_name='login_users')
    op.drop_table('login_users')
    ### end Alembic commands ###
