"""empty message

Revision ID: 88b503dfb9d7
Revises: 29caab165b4d
Create Date: 2016-07-21 07:11:34.443793

"""

# revision identifiers, used by Alembic.
revision = '88b503dfb9d7'
down_revision = '29caab165b4d'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('role_name', sa.String(length=64), nullable=True),
    sa.Column('default', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('role_name')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('roles')
    ### end Alembic commands ###
