"""empty message

Revision ID: 8a004f845307
Revises: 0d688175182d
Create Date: 2016-08-01 23:44:41.950838

"""

# revision identifiers, used by Alembic.
revision = '8a004f845307'
down_revision = '0d688175182d'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vul_reports', sa.Column('done_rank', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vul_reports', 'done_rank')
    ### end Alembic commands ###
