"""empty message

Revision ID: d21a28e53058
Revises: 34115de1f952
Create Date: 2016-08-08 23:36:00.310202

"""

# revision identifiers, used by Alembic.
revision = 'd21a28e53058'
down_revision = '34115de1f952'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('vul_ranks')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vul_ranks',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('date', mysql.DATETIME(), nullable=True),
    sa.Column('name', mysql.VARCHAR(length=64), nullable=True),
    sa.Column('action', mysql.VARCHAR(length=64), nullable=True),
    sa.Column('domain', mysql.VARCHAR(length=64), nullable=True),
    sa.Column('vul_type', mysql.VARCHAR(length=64), nullable=True),
    sa.Column('vul_type_level', mysql.VARCHAR(length=64), nullable=True),
    sa.Column('rank', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('source', mysql.VARCHAR(length=64), nullable=True),
    sa.Column('score', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('validate', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('vul_id', mysql.VARCHAR(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset=u'utf8',
    mysql_engine=u'InnoDB'
    )
    ### end Alembic commands ###
