"""empty message

Revision ID: d64f96086f12
Revises: cb080857529a
Create Date: 2016-06-30 18:08:36.704138

"""

# revision identifiers, used by Alembic.
revision = 'd64f96086f12'
down_revision = 'cb080857529a'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vul_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vul_type', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vul_types_vul_type'), 'vul_types', ['vul_type'], unique=True)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_vul_types_vul_type'), table_name='vul_types')
    op.drop_table('vul_types')
    ### end Alembic commands ###
