"""0629a_add_depart

Revision ID: e3907eac92ed
Revises: 2a6d3c1ab567
Create Date: 2016-06-29 18:45:10.935283

"""

# revision identifiers, used by Alembic.
revision = 'e3907eac92ed'
down_revision = '2a6d3c1ab567'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('departs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('department', sa.String(length=64), nullable=True),
    sa.Column('leader', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_departs_department'), 'departs', ['department'], unique=True)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_departs_department'), table_name='departs')
    op.drop_table('departs')
    ### end Alembic commands ###
